import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { patchDshLayout } from './dsh-layout-patch.mjs';
import { patchDshDocuments } from './dsh-document-patch.mjs';
import { createRuntimePatch } from './runtime-patch.mjs';
import { ensurePlaywrightBrowsers } from './browser-bootstrap.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
await patchDshLayout(root);
await patchDshDocuments(root);
const configPath = path.resolve(process.env.AMADEUS_CONFIG || path.join(root, 'amadeus.local.yml'));
const config = yaml.load(await readFile(configPath, 'utf8'));
if (!config?.username || !config?.password || config.password === 'CHANGE-ME') throw new Error('Set username/password in the private amadeus.local.yml before starting.');
const home = path.resolve(config.home || path.join(root, '.amadeus/dsh-home'));
await mkdir(home, { recursive: true, mode: 0o700 });
await ensurePlaywrightBrowsers({ root, home, config });
const patch = createRuntimePatch({ root, home, config });
const patchPath = path.join(home, 'amadeus.cordis.patch.yml');
await writeFile(patchPath, yaml.dump(patch), { mode: 0o600 });
const cli = path.join(root, 'node_modules/@deepseek-ai/dsh/lib/bin.js');
const initialize = existsSync(path.join(home, 'profiles/amadeus/package.json')) ? [] : ['--from-default-profile', 'web'];
const child = spawn(process.execPath, [cli, '--profile', 'amadeus', ...initialize, '--patch', patchPath, '--no-open', ...process.argv.slice(2)], { cwd: path.resolve(config.workspace || root), env: { ...process.env, DSH_HOME: home }, stdio: 'inherit', windowsHide: true });
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => child.kill(signal));
child.once('exit', code => { process.exitCode = code ?? 1; });
